spring:
  application:
    name: campusmate-backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    
  jpa:
    hibernate:
      ddl-auto: validate   # safer for prod (use update only during dev)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: false

  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400000}   # 24 hours
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
      
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}   # <-- Default to Brevo
    port: ${MAIL_PORT:587}                     # <-- Port for Brevo SMTP
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s

server:
  port: ${PORT:8080}

app:
  frontend:
    url: ${FRONTEND_URL}

logging:
  level:
    com.campusmate: WARN
    org.springframework.security: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      # Enable liveness and readiness probes
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  # Optional: Add more detailed health checks
  metrics:
    export:
      prometheus:
        enabled: false